/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CharacterResponseDto,
  UpgradeStatDto
} from '../model';

import { customInstance } from '../../lib/custom-instance';
import type { ErrorType , BodyType } from '../../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Прокачка характеристик персонажа за Ци
 */
export const characterControllerUpgradeStat = (
    upgradeStatDto: BodyType<UpgradeStatDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CharacterResponseDto>(
      {url: `https://surround-steven-clan-residential.trycloudflare.com/character/upgrade-stat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: upgradeStatDto, signal
    },
      options);
    }



export const getCharacterControllerUpgradeStatMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof characterControllerUpgradeStat>>, TError,{data: BodyType<UpgradeStatDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof characterControllerUpgradeStat>>, TError,{data: BodyType<UpgradeStatDto>}, TContext> => {

const mutationKey = ['characterControllerUpgradeStat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof characterControllerUpgradeStat>>, {data: BodyType<UpgradeStatDto>}> = (props) => {
          const {data} = props ?? {};

          return  characterControllerUpgradeStat(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CharacterControllerUpgradeStatMutationResult = NonNullable<Awaited<ReturnType<typeof characterControllerUpgradeStat>>>
    export type CharacterControllerUpgradeStatMutationBody = BodyType<UpgradeStatDto>
    export type CharacterControllerUpgradeStatMutationError = ErrorType<unknown>

    /**
 * @summary Прокачка характеристик персонажа за Ци
 */
export const useCharacterControllerUpgradeStat = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof characterControllerUpgradeStat>>, TError,{data: BodyType<UpgradeStatDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof characterControllerUpgradeStat>>,
        TError,
        {data: BodyType<UpgradeStatDto>},
        TContext
      > => {
      return useMutation(getCharacterControllerUpgradeStatMutationOptions(options), queryClient);
    }
    /**
 * @summary Совершение ручного прорыва на следующую крупную стадию
 */
export const characterControllerBreakthrough = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CharacterResponseDto>(
      {url: `https://surround-steven-clan-residential.trycloudflare.com/character/breakthrough`, method: 'POST', signal
    },
      options);
    }



export const getCharacterControllerBreakthroughMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof characterControllerBreakthrough>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof characterControllerBreakthrough>>, TError,void, TContext> => {

const mutationKey = ['characterControllerBreakthrough'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof characterControllerBreakthrough>>, void> = () => {


          return  characterControllerBreakthrough(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CharacterControllerBreakthroughMutationResult = NonNullable<Awaited<ReturnType<typeof characterControllerBreakthrough>>>

    export type CharacterControllerBreakthroughMutationError = ErrorType<unknown>

    /**
 * @summary Совершение ручного прорыва на следующую крупную стадию
 */
export const useCharacterControllerBreakthrough = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof characterControllerBreakthrough>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof characterControllerBreakthrough>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCharacterControllerBreakthroughMutationOptions(options), queryClient);
    }
