/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CharacterResponseDto,
  CharacterWithPendingResponseDto,
  UpgradeStatDto,
} from "../model";

import { customInstance } from "../../lib/custom-instance";
import type { ErrorType, BodyType } from "../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить профиль персонажа с учетом накопленной Ци
 */
export const characterControllerGetMe = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CharacterWithPendingResponseDto>(
    {
      url: `https://dicke-animals-grocery-acid.trycloudflare.com/character/me`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getCharacterControllerGetMeQueryKey = () => {
  return [
    `https://dicke-animals-grocery-acid.trycloudflare.com/character/me`,
  ] as const;
};

export const getCharacterControllerGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof characterControllerGetMe>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof characterControllerGetMe>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCharacterControllerGetMeQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof characterControllerGetMe>>
  > = ({ signal }) => characterControllerGetMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof characterControllerGetMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CharacterControllerGetMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof characterControllerGetMe>>
>;
export type CharacterControllerGetMeQueryError = ErrorType<unknown>;

export function useCharacterControllerGetMe<
  TData = Awaited<ReturnType<typeof characterControllerGetMe>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof characterControllerGetMe>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof characterControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof characterControllerGetMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCharacterControllerGetMe<
  TData = Awaited<ReturnType<typeof characterControllerGetMe>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof characterControllerGetMe>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof characterControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof characterControllerGetMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCharacterControllerGetMe<
  TData = Awaited<ReturnType<typeof characterControllerGetMe>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof characterControllerGetMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить профиль персонажа с учетом накопленной Ци
 */

export function useCharacterControllerGetMe<
  TData = Awaited<ReturnType<typeof characterControllerGetMe>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof characterControllerGetMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCharacterControllerGetMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Забрать накопленную пассивную Ци
 */
export const characterControllerClaimQi = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CharacterResponseDto>(
    {
      url: `https://dicke-animals-grocery-acid.trycloudflare.com/character/claim-qi`,
      method: "POST",
      signal,
    },
    options,
  );
};

export const getCharacterControllerClaimQiMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof characterControllerClaimQi>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof characterControllerClaimQi>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["characterControllerClaimQi"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof characterControllerClaimQi>>,
    void
  > = () => {
    return characterControllerClaimQi(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CharacterControllerClaimQiMutationResult = NonNullable<
  Awaited<ReturnType<typeof characterControllerClaimQi>>
>;

export type CharacterControllerClaimQiMutationError = ErrorType<unknown>;

/**
 * @summary Забрать накопленную пассивную Ци
 */
export const useCharacterControllerClaimQi = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof characterControllerClaimQi>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof characterControllerClaimQi>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getCharacterControllerClaimQiMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Прокачка характеристик персонажа за Ци
 */
export const characterControllerUpgradeStat = (
  upgradeStatDto: BodyType<UpgradeStatDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CharacterResponseDto>(
    {
      url: `https://dicke-animals-grocery-acid.trycloudflare.com/character/upgrade-stat`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: upgradeStatDto,
      signal,
    },
    options,
  );
};

export const getCharacterControllerUpgradeStatMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof characterControllerUpgradeStat>>,
    TError,
    { data: BodyType<UpgradeStatDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof characterControllerUpgradeStat>>,
  TError,
  { data: BodyType<UpgradeStatDto> },
  TContext
> => {
  const mutationKey = ["characterControllerUpgradeStat"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof characterControllerUpgradeStat>>,
    { data: BodyType<UpgradeStatDto> }
  > = (props) => {
    const { data } = props ?? {};

    return characterControllerUpgradeStat(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CharacterControllerUpgradeStatMutationResult = NonNullable<
  Awaited<ReturnType<typeof characterControllerUpgradeStat>>
>;
export type CharacterControllerUpgradeStatMutationBody =
  BodyType<UpgradeStatDto>;
export type CharacterControllerUpgradeStatMutationError = ErrorType<unknown>;

/**
 * @summary Прокачка характеристик персонажа за Ци
 */
export const useCharacterControllerUpgradeStat = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof characterControllerUpgradeStat>>,
      TError,
      { data: BodyType<UpgradeStatDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof characterControllerUpgradeStat>>,
  TError,
  { data: BodyType<UpgradeStatDto> },
  TContext
> => {
  return useMutation(
    getCharacterControllerUpgradeStatMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Совершение ручного прорыва на следующую крупную стадию
 */
export const characterControllerBreakthrough = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CharacterResponseDto>(
    {
      url: `https://dicke-animals-grocery-acid.trycloudflare.com/character/breakthrough`,
      method: "POST",
      signal,
    },
    options,
  );
};

export const getCharacterControllerBreakthroughMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof characterControllerBreakthrough>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof characterControllerBreakthrough>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["characterControllerBreakthrough"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof characterControllerBreakthrough>>,
    void
  > = () => {
    return characterControllerBreakthrough(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CharacterControllerBreakthroughMutationResult = NonNullable<
  Awaited<ReturnType<typeof characterControllerBreakthrough>>
>;

export type CharacterControllerBreakthroughMutationError = ErrorType<unknown>;

/**
 * @summary Совершение ручного прорыва на следующую крупную стадию
 */
export const useCharacterControllerBreakthrough = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof characterControllerBreakthrough>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof characterControllerBreakthrough>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getCharacterControllerBreakthroughMutationOptions(options),
    queryClient,
  );
};
