/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */
import type { CharacterResponseDtoAvatar } from './characterResponseDtoAvatar';

export interface CharacterResponseDto {
  id: string;
  userId: string;
  name: string;
  avatar: CharacterResponseDtoAvatar;
  stage: number;
  level: number;
  exp: number;
  strength: number;
  spirit: number;
  agility: number;
  constitution: number;
  maxHp: number;
  hp: number;
}
