/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */

export interface CharacterWithPendingResponseDto {
  id: string;
  userId: string;
  stage: number;
  level: number;
  exp: number;
  strength: number;
  spirit: number;
  agility: number;
  constitution: number;
  maxHp: number;
  hp: number;
  lastClaimAt: string;
  /** Накопленная Ци, готовая к сбору */
  pendingQi: number;
  /** Заполнен ли склад пассивного дохода */
  isStorageFull: boolean;
  /** Сколько секунд осталось до полного заполнения склада */
  storageSecondsLeft: number;
}
