/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */
import type { DbUserDtoAllowsWriteToPm } from "./dbUserDtoAllowsWriteToPm";
import type { DbUserDtoLanguageCode } from "./dbUserDtoLanguageCode";
import type { DbUserDtoLastName } from "./dbUserDtoLastName";
import type { DbUserDtoPhotoUrl } from "./dbUserDtoPhotoUrl";
import type { DbUserDtoUsername } from "./dbUserDtoUsername";

export interface DbUserDto {
  id: string;
  telegramId: string;
  /** @nullable */
  username?: DbUserDtoUsername;
  firstName: string;
  /** @nullable */
  lastName?: DbUserDtoLastName;
  /** @nullable */
  languageCode?: DbUserDtoLanguageCode;
  allowsWriteToPm?: DbUserDtoAllowsWriteToPm;
  /** @nullable */
  photoUrl?: DbUserDtoPhotoUrl;
  createdAt: string;
  updatedAt: string;
}
