/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */

export * from './telegramLoginRequestDto';
export * from './telegramLoginResponseDto';
export * from './telegramUserDto';
