/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */

export interface MeditationResponseDto {
  id: string;
  characterId: string;
  duration: number;
  rewardExp: number;
  status: string;
  startedAt: string;
  endsAt: string;
  updatedAt: string;
}
