/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */
import type { MeditationResponseDto } from './meditationResponseDto';

export interface MeditationStateResponseDto {
  active: boolean;
  /** @nullable */
  meditation: MeditationResponseDto | null;
}
