/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */

export interface StartMeditationDto {
  /**
     * Длительность медитации в часах
     * @minimum 1
     * @maximum 8
     */
  hours: number;
}
