/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */
import type { DbUserDto } from "./dbUserDto";

export interface TelegramLoginResponseDto {
  token: string;
  user: DbUserDto;
}
