/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */

export interface TelegramUserDto {
  id: number;
  first_name: string;
  last_name?: string;
  username?: string;
  language_code?: string;
}
