/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */
export interface TelegramLoginRequestDto {
  initData: string;
}

export interface TelegramUserDto {
  id: number;
  first_name: string;
  last_name?: string;
  username?: string;
  language_code?: string;
}

export interface TelegramLoginResponseDto {
  token: string;
  user: TelegramUserDto;
}

export type authControllerLoginResponse200 = {
  data: TelegramLoginResponseDto
  status: 200
}

export type authControllerLoginResponseSuccess = (authControllerLoginResponse200) & {
  headers: Headers;
};
;

export type authControllerLoginResponse = (authControllerLoginResponseSuccess)

export const getAuthControllerLoginUrl = () => {




  return `/auth/telegram`
}

export const authControllerLogin = async (telegramLoginRequestDto: TelegramLoginRequestDto, options?: RequestInit): Promise<authControllerLoginResponse> => {

  const res = await fetch(getAuthControllerLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(telegramLoginRequestDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authControllerLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerLoginResponse
}
