/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * TG Game API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MeditationResponseDto,
  MeditationStateResponseDto,
  StartMeditationDto
} from '../model';

import { customInstance } from '../../lib/custom-instance';
import type { ErrorType , BodyType } from '../../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Получить текущее состояние медитации
 */
export const meditationControllerGetState = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<MeditationStateResponseDto>(
      {url: `https://applying-terminology-tub-mardi.trycloudflare.com/meditation`, method: 'GET', signal
    },
      options);
    }




export const getMeditationControllerGetStateQueryKey = () => {
    return [
    `https://applying-terminology-tub-mardi.trycloudflare.com/meditation`
    ] as const;
    }


export const getMeditationControllerGetStateQueryOptions = <TData = Awaited<ReturnType<typeof meditationControllerGetState>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meditationControllerGetState>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeditationControllerGetStateQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof meditationControllerGetState>>> = ({ signal }) => meditationControllerGetState(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof meditationControllerGetState>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeditationControllerGetStateQueryResult = NonNullable<Awaited<ReturnType<typeof meditationControllerGetState>>>
export type MeditationControllerGetStateQueryError = ErrorType<unknown>


export function useMeditationControllerGetState<TData = Awaited<ReturnType<typeof meditationControllerGetState>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof meditationControllerGetState>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meditationControllerGetState>>,
          TError,
          Awaited<ReturnType<typeof meditationControllerGetState>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeditationControllerGetState<TData = Awaited<ReturnType<typeof meditationControllerGetState>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meditationControllerGetState>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meditationControllerGetState>>,
          TError,
          Awaited<ReturnType<typeof meditationControllerGetState>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeditationControllerGetState<TData = Awaited<ReturnType<typeof meditationControllerGetState>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meditationControllerGetState>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить текущее состояние медитации
 */

export function useMeditationControllerGetState<TData = Awaited<ReturnType<typeof meditationControllerGetState>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meditationControllerGetState>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeditationControllerGetStateQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Начать медитацию
 */
export const meditationControllerStart = (
    startMeditationDto: BodyType<StartMeditationDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<MeditationResponseDto>(
      {url: `https://applying-terminology-tub-mardi.trycloudflare.com/meditation/start`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startMeditationDto, signal
    },
      options);
    }



export const getMeditationControllerStartMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof meditationControllerStart>>, TError,{data: BodyType<StartMeditationDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof meditationControllerStart>>, TError,{data: BodyType<StartMeditationDto>}, TContext> => {

const mutationKey = ['meditationControllerStart'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof meditationControllerStart>>, {data: BodyType<StartMeditationDto>}> = (props) => {
          const {data} = props ?? {};

          return  meditationControllerStart(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MeditationControllerStartMutationResult = NonNullable<Awaited<ReturnType<typeof meditationControllerStart>>>
    export type MeditationControllerStartMutationBody = BodyType<StartMeditationDto>
    export type MeditationControllerStartMutationError = ErrorType<unknown>

    /**
 * @summary Начать медитацию
 */
export const useMeditationControllerStart = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof meditationControllerStart>>, TError,{data: BodyType<StartMeditationDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof meditationControllerStart>>,
        TError,
        {data: BodyType<StartMeditationDto>},
        TContext
      > => {
      return useMutation(getMeditationControllerStartMutationOptions(options), queryClient);
    }
    /**
 * @summary Прервать медитацию
 */
export const meditationControllerCancel = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<MeditationResponseDto>(
      {url: `https://applying-terminology-tub-mardi.trycloudflare.com/meditation/cancel`, method: 'POST', signal
    },
      options);
    }



export const getMeditationControllerCancelMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof meditationControllerCancel>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof meditationControllerCancel>>, TError,void, TContext> => {

const mutationKey = ['meditationControllerCancel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof meditationControllerCancel>>, void> = () => {


          return  meditationControllerCancel(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MeditationControllerCancelMutationResult = NonNullable<Awaited<ReturnType<typeof meditationControllerCancel>>>

    export type MeditationControllerCancelMutationError = ErrorType<unknown>

    /**
 * @summary Прервать медитацию
 */
export const useMeditationControllerCancel = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof meditationControllerCancel>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof meditationControllerCancel>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getMeditationControllerCancelMutationOptions(options), queryClient);
    }
